### PR TITLE
Preinst fixes for #300

### PR DESCRIPTION
**Pull request by joshuajaharwood**
This fixes sed failing when files don't exist and preventing installation, as well as also editing the systemd service in addition to /etc/default/raspotify.

Discussed in #300.

### CODE REVIEW

**Comment by dtcooper** [comment]
Sorry for the delay, dealing with a bit of a COVID situation here. Will get to this ASAP.

**Comment by JasonLG1979** [comment]
> Sorry for the delay, dealing with a bit of a COVID situation here. Will get to this ASAP.

I had a bit of a COVID scare a couple weeks ago myself. I hope I speak for everyone when I say take all the time you need and we wish you well. Real life and the health of you and all the people around you is vastly more important then raspotify.

**Comment by joshuajaharwood** [comment]
@dtcooper Sorry to hear it. Hope any recoveries go well <3

**Comment by dtcooper** [comment]
Hey all! Doing well! @joshuajaharwood, I don't think we need the check + sed in `/etc/systemd/system/raspotify.service` because _I believe_ it gets updated when the package gets updated. Do you have any reason to believe it doesn't? I observe that in testing.

**Comment by joshuajaharwood** [comment]
You're quite possibly write, I just adapted what was stated in the thread and assumed the service didn't get updated. Will report back shortly to confirm.

**Comment by joshuajaharwood** [comment]
@dtcooper Just tried the following:

1. Apt purged raspotify
2. Installed it from your apt repo (service has --linear-volume)
  `sudo apt install raspotify`
3. Install my build based on my fork (with the service sed commented out)
  `sudo apt install ./raspotify_test.deb`
4. Service still has --linear-volume, won't start as a result. /etc/default has been updated.

**Comment by joshuajaharwood** [comment]
Oh, I also found that purging didn't remove the service file. Be sure to delete it if you try the same out!

**Comment by JasonLG1979** [comment]
The default behavior is to just disable and mask the service file on purge. It doesn't completely remove the service file which is what you should expect when purging a package I would think? In my mind purge means remove all trace, not the case here. The  ```deb-systemd-helper``` docs aren't very clear. I'm not even sure why ```deb-systemd-helper``` is used when ```systemctl``` and ```rm``` would be more clear as to what is actually happening and would actually do what you'd expect. Again completely disable the service and delete the service file.

When updating the behavior seems to be to not change the service file, which normally is a good idea since it's very possible that a user may have edited the service file. (I have) but in the case of breaking changes you'd want to fix the breakages.

**Comment by dtcooper** [comment]
Not accepting this commit, since I'm going to do this is `postinst`, however your idea is what is going to help close this, @joshuajaharwood so THANK YOU! 😄

**Pull request closed without merging**
