### PR TITLE
Update configuration template for upstream 0.5.0

### LINKED ISSUE #673: Invalid --autoplay / -A in librespot
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

Raspotify worked for years and stopped today.

service raspotify status shows:
set 18 09:38:08 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
set 18 09:38:08 raspberrypi librespot[7213]: [2024-09-18T12:38:08Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:38:08 raspberrypi librespot[7213]: Valid `--autoplay` / `-A` values: on, off
set 18 09:38:08 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:38:08 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:38:08 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
-- System Info --

Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

-- Logs --

set 18 09:37:10 raspberrypi librespot[5420]: [2024-09-18T12:37:05Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:37:10 raspberrypi librespot[5420]: Valid `--autoplay` / `-A` values: on, off
set 18 09:37:05 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:37:05 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:37:05 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.
set 18 09:37:21 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
set 18 09:37:21 raspberrypi librespot[5784]: [2024-09-18T12:37:21Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:37:21 raspberrypi librespot[5784]: Valid `--autoplay` / `-A` values: on, off
set 18 09:37:21 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:37:21 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:37:21 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.
set 18 09:37:33 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
set 18 09:37:33 raspberrypi librespot[6142]: [2024-09-18T12:37:33Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:37:33 raspberrypi librespot[6142]: Valid `--autoplay` / `-A` values: on, off
set 18 09:37:33 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:37:33 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:37:33 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.
set 18 09:37:44 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
set 18 09:37:44 raspberrypi librespot[6499]: [2024-09-18T12:37:44Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:37:44 raspberrypi librespot[6499]: Valid `--autoplay` / `-A` values: on, off
set 18 09:37:44 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:37:44 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:37:44 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.
set 18 09:37:56 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
set 18 09:37:56 raspberrypi librespot[6856]: [2024-09-18T12:37:56Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:37:56 raspberrypi librespot[6856]: Valid `--autoplay` / `-A` values: on, off
set 18 09:37:56 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:37:56 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:37:56 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.
set 18 09:38:08 raspberrypi systemd[1]: Started Raspotify (Spotify Connect Client).
set 18 09:38:08 raspberrypi librespot[7213]: [2024-09-18T12:38:08Z ERROR librespot] Invalid `--autoplay` / `-A`: ""
set 18 09:38:08 raspberrypi librespot[7213]: Valid `--autoplay` / `-A` values: on, off
set 18 09:38:08 raspberrypi systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
set 18 09:38:08 raspberrypi systemd[1]: raspotify.service: Failed with result 'exit-code'.
set 18 09:38:08 raspberrypi systemd[1]: raspotify.service: Triggering OnFailure= dependencies.

-- Config --

LIBRESPOT_QUIET=
LIBRESPOT_AUTOPLAY=
LIBRESPOT_DISABLE_AUDIO_CACHE=
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
LIBRESPOT_NAME="Raspotify (Boxe)"
LIBRESPOT_DEVICE="plughw:CARD=Headphones,DEV=0"
LIBRESPOT_INITIAL_VOLUME="100"

-- Ouput of aplay -l --

**** List of PLAYBACK Hardware Devices ****
card 0: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: vc4hdmi [vc4-hdmi], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

-- Ouput of aplay -L --

null
    Discard all samples (playback) or generate zero samples (capture)
lavrate
    Rate Converter Plugin Using Libav/FFmpeg Library
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
default:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output
hw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
default:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct sample mixing device
usbstream:CARD=vc4hdmi
    vc4-hdmi
    USB Stream Output

-- Ouput of librespot -d ? --


        Compatible alsa device(s):

        ------------------------------------------------------

        Device:

                hw:CARD=Headphones,DEV=0

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Direct hardware device without any conversions

        Supported Format(s):

                S16

        ------------------------------------------------------

        Device:

                plughw:CARD=Headphones,DEV=0

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Hardware device with all software conversions

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                default:CARD=Headphones

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Default Audio Device

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                sysdefault:CARD=Headphones

        Description:

                bcm2835 Headphones, bcm2835 Headphones
                Default Audio Device

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                default:CARD=vc4hdmi

        Description:

                vc4-hdmi, MAI PCM i2s-hifi-0
                Default Audio Device

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                sysdefault:CARD=vc4hdmi

        Description:

                vc4-hdmi, MAI PCM i2s-hifi-0
                Default Audio Device

        Supported Format(s):

                S16 S24 S24_3 S32 F32 F64

        ------------------------------------------------------

        Device:

                hdmi:CARD=vc4hdmi,DEV=0

        Description:

                vc4-hdmi, MAI PCM i2s-hifi-0
                HDMI Audio Output

        Supported Format(s):

                S16 S24 S24_3 S32

        ------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by kimtore**
* Removes LIBRESPOT_SAMPLE_RATE
* Removes LIBRESPOT_INTERPOLATION_QUALITY
* Sets boolean values in config to 'on' or 'off'

Fixes #673

### CODE REVIEW

**Comment by MichaIng** [comment]
Do these values match the previous defaults when the variables were empty or unset?

**Comment by kimtore** [comment]
@MichaIng, yes, to the best of my knowledge :)

**Comment by codydubat** [comment]
Did you test this @kimtore? In librespot help (librespot -h) only autoplay flag mentions it expects {on|off}. The others are just regular flags. 
Look at `--quiet` for example:
image
I also tried to update the config and make a PR but I am not familiar with Rust and only from the bash files I couldn't figure out how these variables actually get parsed.
To me it looks like {on | off} applies only to autoplay while the others are just regular flags. Please correct me if I am wrong.
And even then I wasn't able to actually get autoplay working no matter if I set it as `on` or "on" or 'on'. The only thing I know is that no matter what you set there at least it doesn't crash on start.
If you know how the parsing works, I can also pick this up

**Comment by MichaIng** [comment]
Actually, "Defaults to following the client setting." indicates that with this commit, Raspotify indeed does change/override the defaults, and that all those empty-value settings should be commented to preserve the previous behaviour.

**Comment by bonzi9** [comment]
@codydubat 
I suspect the same thing, where the new default autoplay behavior of librespot is not specifying any --autoplay flag to let the client setting for autoplay decide what librespot should do.

So far I can confirm that commenting out the setting like this: `#LIBRESPOT_AUTOPLAY=on`, the debug log shows that it switches on and off when I toggle the autoplay setting in the Spotify android app:

OFF:
`Sep 25 17:23:29 DietPi-NUC librespot[1672]: [2024-09-25T15:23:29Z TRACE librespot_connect::spirc] Received attribute mutation, autoplay was 1 is now 0`
`Sep 25 17:23:29 DietPi-NUC librespot[1672]: [2024-09-25T15:23:29Z DEBUG librespot_playback::player] command=EmitAutoPlayChangedEvent(false)`

ON:
`Sep 25 17:23:50 DietPi-NUC librespot[1672]: [2024-09-25T15:23:50Z TRACE librespot_connect::spirc] Received attribute mutation, autoplay was 0 is now 1`
`Sep 25 17:23:50 DietPi-NUC librespot[1672]: [2024-09-25T15:23:50Z DEBUG librespot_playback::player] command=EmitAutoPlayChangedEvent(true)`

When enabling the setting in the conf file to either `LIBRESPOT_AUTOPLAY=on` or `LIBRESPOT_AUTOPLAY=off` that results in librespot ignoring it as expected when toggling the autoplay option in the app:

`Sep 25 17:25:39 DietPi-NUC librespot[1724]: [2024-09-25T15:25:39Z TRACE librespot_connect::spirc] Autoplay override active. Ignoring mutation.`

But also like you mentioned, I also cannot get autoplay to work either by commenting out the setting or setting it to `=on`.

**Comment by codydubat** [comment]
@bonzi9 Great! Thanks for the deep dive! Then should we remove this param completely from the default conf? @kimtore @dtcooper ?

**Comment by bonzi9** [comment]
If I may suggest, I would leave the option in the file but commented out so that the default behavior is to allow librespot to respect the client setting, and so it is clear that it can be forced/adjusted, but just not left empty if set active.
Something like this as default:

`# Automatically play similar songs when your music ends.`
`# Respects client autoplay setting if commented out. Forces autoplay on or off when active.`
`# If active the value must be specified, or librespot will fail to start.`
`#LIBRESPOT_AUTOPLAY=on`

**Comment by kimtore** [comment]
@bonzi9 thank you, these changes will be included with the next release.

**Pull request merged**
