### PR TITLE
added normalisation-pregain option to config file

### PR DESCRIPTION
**Pull request by pimvh**
First of all, thanks for the great repository!

I personally had some issues with low levels of default sound, and saw the additional --normalisation-pregain option in the librespot docs. This PR is quite simple, I've added this to the VOLUME_ARGS. I think this option might help other users quickly to solve issues with low volumes.

This is my first pull-request, so if I submitted this in the wrong way, please forgive me!

### CODE REVIEW

**Comment by dtcooper** [comment]
Thanks! May be better to add this to README.md, since I'm not sure adding this merits the Debian package hiccup one will get comparing their old conffile with the new. Thoughts?

**Comment by pimvh** [comment]
I don't know what you mean with respects to the Debian package hiccup. Adding it to the README is fine with me! 

Do you want me to close this?

**Comment by dtcooper** [comment]
@pimvh A PR adding info the README would be great, or you can close out if you don't feel like that. :)

**Comment by pimvh** [comment]
I've created a new PR (#378), had already deleted my previous fork.

**Pull request closed without merging**
