### PR TITLE
point to my librespot: default volume to 50%

### PR DESCRIPTION
**Pull request by fossedihelm**
Since Paul Liétar declared librespot unmaintained I fork his repo to modify librespot default volume. My librespot is the same of Paul Liétar. Just changed the default volume to 50% (in Paul Liétar version is 100%). This provide a better control on volume: before, once connected, you can only turn down the volume; now you can turn it down or up as you want.

### CODE REVIEW

**Comment by balintkozma** [comment]
I disagree.

The lower the volume of the pre-amp (pi), the higher the gain of the power-amp, the higher the noise added to the signal. 
(It can be understood with common sense: suppose we are at 0.01% volume, then we amplify it 1000 times to hear it, we end up getting almost nothing just noise.)
Digital signals also have noise (quantization noise), which we don't want to amplify.

So the pre-amp should be at maximum level. Leave it at 100%
Control the gain of the power-amp, not the volume level of the pi.

**Comment by fossedihelm** [comment]
You're right, but in my opinion we have to find a tradeoff between the quantity of noise and the user experience. However I think that PR can be closed because dtcooper is finding a new librespot official fork.

**Comment by l3d00m** [comment]
https://github.com/ComlOnline/librespot

This branch merged together some features of other branches, it looks like the most promising to me at the moment.

**Comment by ComlOnline** [comment]
Just as an update https://github.com/librespot-org/librespot has been created. We hope to continue the work there. Also its based around an organisation so can't go stale as easily. And as you know it has the --inital-volume tag you implemented. librespot-org/librespot#5

**Comment by dtcooper** [comment]
I've updated Raspotify to use this fork so it should fix this and a variety of other issues. Closing and thanks!

**Pull request closed without merging**
